apiVersion: v1
kind: Secret
metadata:
  name: payment-postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: "payment_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "jama"

  DB_USER: "posgres"
  DB_PASSWORD: "jama"
  DB_HOST: "payment-postgres"
  DB_PORT: "5432"
  DB_NAME: "payment_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-app-secret
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "dfnjn3uvnrui"
  YOOKASSA_SHOP_ID: "1186082"
  YOOKASSA_SECRET_KEY: "test_d3RDJgqcOJPyIYbouOHASv0iIHsU29mItxr_LvEeLKI"
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: default
type: Opaque
stringData:
  KAFKA_HOST: "92.53.115.20:9092"
  KAFKA_USERNAME: "gen_user"
  KAFKA_PASSWORD: "testoviyparol"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: "order_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "jama"

  DB_USER: "posgres"
  DB_PASSWORD: "jama"
  DB_HOST: "order-postgres"
  DB_PORT: "5432"
  DB_NAME: "order_db"